apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktakapp-deployment
spec:
  replicas: 3 # Number of Nginx pods to run
  selector:
    matchLabels:
      app: tiktak
  template:
    metadata:
      labels:
        app: tiktak
    spec:
      containers:
      - name: tiktak
        image: praveenkumar90400/tiktakapp:latest
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: tiktak-service
spec:
  selector:
    app: tiktak
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # Or NodePort, depending on your needs
