apiVersion: v1
kind: Service
metadata:
  name: invent-service
spec:
  selector:
    app: invent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # Or NodePort, depending on your needs
