apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventapp-deployment
spec:
  replicas: 3 # Number of Nginx pods to run
  selector:
    matchLabels:
      app: invent
  template:
    metadata:
      labels:
        app: invent
    spec:
      containers:
      - name: invent
        image: praveenkumar90400/inventapp:latest
        ports:
        - containerPort: 80
